### ISSUE TITLE
Testing on Windows

### ISSUE THREAD

**Issue by PhiLhoSoft** [akashacms/akashacms#136]
I try to use AkashaCMS on Windows 7.
I have Node.js and Git already installed.
I started to follow the instructions at http://akashacms.com/install.html
Including the part where you tell not to use `-g`. Here, it would be interesting to tell why we should not install it globally... Anyway, I don't plan to make lot of sites, so I don't mind a local installation. But that's some 40 MB installed, for the record...
Problem: "_After this step npm will have created a directory named node_modules containing two directories, one named .bin and the other named akashacm_". Well, no, I just have a akashcms directory, not a .bin one.
OK, I see an `cli.js` file in the folder, let's try to run it.
`node node_modules\akashacms\cli.js init PLS` works.
`node ..\node_modules\akashacms\cli.js build` fails, complaining it "_Cannot find module 'akashacms-theme-bootstrap'_".
Looks not a major problem, as it is referenced in the package.json. `npm install` reinstalls akashacms (sigh) and the needed modules. Then the build command works.
I stop here for today, I thought I could share my findings, if you want to update your doc.
For reference, I give below a transcript of my session:

```
D:\PhiLhoSoft\Web
> md AkashaCMSTest

D:\PhiLhoSoft\Web
> cd AkashaCMSTest\

D:\PhiLhoSoft\Web\AkashaCMSTest
> npm install akashacms
akashacms@0.4.14 node_modules\akashacms
+-- basic-auth@1.0.3
+-- sightmap@0.0.1
+-- mahabhuta@0.4.2
+-- kernel@0.1.4
+-- mime@1.3.4
+-- formidable@1.0.17
+-- commander@2.9.0 (graceful-readlink@1.0.1)
+-- async@1.5.0
+-- body@5.1.0 (continuable-cache@0.3.1, safe-json-parse@1.0.1, raw-body@1.1.7, error@7.0.2)
+-- oembed@0.1.0 (htmlparser@1.7.7)
+-- sseasy@2.0.1 (through2@0.6.5)
+-- ejs@2.3.4
+-- globfs@0.1.1 (glob@5.0.15)
+-- body-parser@1.14.1 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.4, debug@2.2.0, qs@5.1.0, type-is@1.6.9, iconv-lite@0.4.12)
+-- fs-extra@0.26.2 (path-is-absolute@1.0.0, jsonfile@2.2.3, klaw@1.1.1, graceful-fs@4.1.2, rimraf@2.4.3)
+-- express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, array-flatten@1.1.1, methods@1.1.1, cookie-signature@1.0.6, utils-merge@1.0.0, fresh@0.3.0, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, finalhandler@0.4.0, on-finished@2.3.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.9, accepts@1.2.13)
+-- request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.1, form-data@1.0.0-rc3, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.3, qs@5.2.0, mime-types@2.1.7, tough-cookie@2.2.0, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.1)
+-- log4js@0.6.27 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
+-- rss@1.2.0 (xml@1.0.0, mime-types@2.1.7, grunt-cli@0.1.13)
+-- ssh2sync@0.0.15 (filewalker@0.1.2, ssh2@0.4.12)
+-- node-zip@1.1.1 (jszip@2.5.0)
+-- yfm@0.2.0 (delims@0.1.4, fs-utils@0.1.11, lodash@2.4.2, js-yaml@3.0.2)
+-- minify@2.0.0 (try-catch@1.0.0, rendy@1.1.0, execon@1.2.9, debug@2.2.0, tomas@1.0.2, html-minifier@1.0.0, clean-css@3.4.7, css-b64-images@0.2.5, uglify-js@2.5.0)
+-- archiver@0.16.0 (buffer-crc32@0.2.5, async@1.4.2, lazystream@0.1.0, readable-stream@1.0.33, glob@5.0.15, zip-stream@0.6.0, tar-stream@1.2.2, lodash@3.10.1)
+-- cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3, lodash@3.10.1)
+-- markdown-it@5.0.1 (uc.micro@1.0.0, mdurl@1.0.1, linkify-it@1.2.0, entities@1.1.1, argparse@1.0.3)
+-- less@2.5.3 (graceful-fs@3.0.8, image-size@0.3.5, errno@0.1.4, promise@6.1.0, source-map@0.4.4, mkdirp@0.5.1)

D:\PhiLhoSoft\Web\AkashaCMSTest
> node node_modules\akashacms\cli.js

D:\PhiLhoSoft\Web\AkashaCMSTest
> node node_modules\akashacms\cli.js init .
fatal: destination path '.' already exists and is not an empty directory.

D:\PhiLhoSoft\Web\AkashaCMSTest
> node node_modules\akashacms\cli.js init PLS
Cloning into 'PLS'...
remote: Counting objects: 297, done.
remote: Total 297 (delta 0), reused 0 (delta 0), pack-reused 297
Receiving objects: 100% (297/297), 197.74 KiB | 0 bytes/s, done.
Resolving deltas: 100% (129/129), done.
Checking connectivity... done.

D:\PhiLhoSoft\Web\AkashaCMSTest
> cd PLS\

D:\PhiLhoSoft\Web\AkashaCMSTest\PLS
> node ..\node_modules\akashacms\cli.js build
module.js:338
    throw err;
          ^
Error: Cannot find module 'akashacms-theme-bootstrap'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.config (D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\config.js:83:58)
    at Object.module.exports.config (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\index.js:136:16)

    at Command.<anonymous> (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\cli.js:86:16)
    at Command.listener (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\node_modules\commander\index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\node_modules\commander\index.js:615:12)

D:\PhiLhoSoft\Web\AkashaCMSTest\PLS
> node ..\node_modules\akashacms\cli.js config
module.js:338
    throw err;
          ^
Error: Cannot find module 'akashacms-theme-bootstrap'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.config (D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\config.js:83:58)
    at Object.module.exports.config (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\index.js:136:16)

    at Command.<anonymous> (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\cli.js:310:16)
    at Command.listener (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\node_modules\commander\index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (D:\PhiLhoSoft\Web\AkashaCMSTest\node_modules\akashacms\node_modules\commander\index.js:615:12)

D:\PhiLhoSoft\Web\AkashaCMSTest\PLS
> npm install
akashacms-base@0.4.4 node_modules\akashacms-base
+-- async@1.5.0

akashacms-booknav@0.4.3 node_modules\akashacms-booknav
+-- async@1.5.0

akashacms-theme-bootstrap@0.4.2 node_modules\akashacms-theme-bootstrap

akashacms-embeddables@0.4.3 node_modules\akashacms-embeddables
+-- async@1.5.0
+-- request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, tunnel-agent@0.4.1, oauth-sign@0.8.0, form-data@1.0.0-rc3, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.1, har-validator@2.0.2)
+-- youtube-node@1.3.0 (colors@1.0.3, request@2.53.0, prompt@0.2.14)

akashacms@0.4.14 node_modules\akashacms
+-- basic-auth@1.0.3
+-- sightmap@0.0.1
+-- mahabhuta@0.4.2
+-- mime@1.3.4
+-- kernel@0.1.4
+-- formidable@1.0.17
+-- commander@2.9.0 (graceful-readlink@1.0.1)
+-- async@1.5.0
+-- body@5.1.0 (continuable-cache@0.3.1, safe-json-parse@1.0.1, raw-body@1.1.7, error@7.0.2)
+-- sseasy@2.0.1 (through2@0.6.5)
+-- globfs@0.1.1 (glob@5.0.15)
+-- oembed@0.1.0 (htmlparser@1.7.7)
+-- ejs@2.3.4
+-- body-parser@1.14.1 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, http-errors@1.3.1, on-finished@2.3.0, raw-body@2.1.4, debug@2.2.0, qs@5.1.0, type-is@1.6.9, iconv-lite@0.4.12)
+-- express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, utils-merge@1.0.0, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, serve-static@1.10.0, content-disposition@0.5.0, depd@1.0.1, finalhandler@0.4.0, on-finished@2.3.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.9, accepts@1.2.13)
+-- fs-extra@0.26.2 (path-is-absolute@1.0.0, klaw@1.1.1, jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.3)
+-- request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, oauth-sign@0.8.0, form-data@1.0.0-rc3, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.3, qs@5.2.0, mime-types@2.1.7, tough-cookie@2.2.0, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.1)
+-- log4js@0.6.27 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
+-- rss@1.2.0 (xml@1.0.0, mime-types@2.1.7, grunt-cli@0.1.13)
+-- ssh2sync@0.0.15 (filewalker@0.1.2, ssh2@0.4.12)
+-- node-zip@1.1.1 (jszip@2.5.0)
+-- minify@2.0.0 (try-catch@1.0.0, rendy@1.1.0, execon@1.2.9, debug@2.2.0, tomas@1.0.2, html-minifier@1.0.0, clean-css@3.4.7, css-b64-images@0.2.5, uglify-js@2.5.0)
+-- yfm@0.2.0 (delims@0.1.4, fs-utils@0.1.11, lodash@2.4.2, js-yaml@3.0.2)
+-- archiver@0.16.0 (buffer-crc32@0.2.5, async@1.4.2, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.6.0, glob@5.0.15, tar-stream@1.2.2, lodash@3.10.1)
+-- cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3, lodash@3.10.1)
+-- markdown-it@5.0.1 (uc.micro@1.0.0, mdurl@1.0.1, linkify-it@1.2.0, entities@1.1.1, argparse@1.0.3)
+-- less@2.5.3 (graceful-fs@3.0.8, image-size@0.3.5, promise@6.1.0, source-map@0.4.4, errno@0.1.4, mkdirp@0.5.1)

D:\PhiLhoSoft\Web\AkashaCMSTest\PLS
> node node_modules\akashacms\cli.js config
[2015-11-10 18:43:37.494] [INFO] console - dirname: D:\PhiLhoSoft\Web\AkashaCMSTest\PLS
[2015-11-10 18:43:37.498] [INFO] console - output directory: out
[2015-11-10 18:43:37.499] [INFO] console -
[2015-11-10 18:43:37.499] [INFO] console - documents directories:
[2015-11-10 18:43:37.499] [INFO] console -      documents
[2015-11-10 18:43:37.500] [INFO] console -
[2015-11-10 18:43:37.500] [INFO] console - assets directories:
[2015-11-10 18:43:37.500] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-embeddables\assets
[2015-11-10 18:43:37.501] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-theme-bootstrap\bootstrap
[2015-11-10 18:43:37.501] [INFO] console -      assets
[2015-11-10 18:43:37.501] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-base\assets
[2015-11-10 18:43:37.502] [INFO] console -
[2015-11-10 18:43:37.502] [INFO] console - partials directories:
[2015-11-10 18:43:37.502] [INFO] console -      partials
[2015-11-10 18:43:37.503] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-theme-bootstrap\partials
[2015-11-10 18:43:37.503] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-embeddables\partials
[2015-11-10 18:43:37.504] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-booknav\partials
[2015-11-10 18:43:37.504] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-base\partials
[2015-11-10 18:43:37.505] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms\builtin\partials
[2015-11-10 18:43:37.505] [INFO] console -
[2015-11-10 18:43:37.506] [INFO] console - layouts directories:
[2015-11-10 18:43:37.506] [INFO] console -      layouts
[2015-11-10 18:43:37.506] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-theme-bootstrap\layout
[2015-11-10 18:43:37.507] [INFO] console -      D:\PhiLhoSoft\Web\AkashaCMSTest\PLS\node_modules\akashacms-base\layout
[2015-11-10 18:43:37.507] [INFO] console -
[2015-11-10 18:43:37.507] [INFO] console - plugins:
[2015-11-10 18:43:37.508] [INFO] console -      akashacms-theme-bootstrap
[2015-11-10 18:43:37.508] [INFO] console -      akashacms-embeddables
[2015-11-10 18:43:37.508] [INFO] console -      akashacms-booknav
[2015-11-10 18:43:37.509] [INFO] console -      akashacms-base
[2015-11-10 18:43:37.509] [INFO] console -      builtin
[2015-11-10 18:43:37.509] [INFO] console -
[2015-11-10 18:43:37.511] [INFO] console - data: { metarobots: 'index,follow',
  metaOGtype: 'website',
  metaOGsite_name: 'AkashaCMS example website',
  metasubject: 'AkashaCMS',
  metalanguage: 'EN' }
```
Project looks fairly complete and interesting, I hope to be able to use it. Thanks.

**Comment by robogeek** [comment]
Can you help me straighten this out?  I don't currently have access to a Windows machine.  

I did write that section of the install page after installing an earlier version of AkashaCMS on Windows.  I vaguely recall running into a difficulty after trying `npm install -g akashacms` but I don't recall what it was.

Please try the instructions in the previous segment of the page:

```
$ npm install akashacms-cli
$ npm install akashacms
```

Then tell me whether a .bin directory shows up.  Earlier this year I developed akashacms-cli and the akashacms package no longer advertises its copy of `cli.js` as a command-line tool, and instead the `cli.js` in akashacms-cli is the command tool.

**Comment by robogeek** [comment]
I do see there's a missing step.  After running "akashacms init" it's now necessary to do "npm install".

**Comment by robogeek** [comment]
What might work is (tested on my Linux system to work):

```
$ mkdir t
$ cd t
$ npm install akashacms-cli
# There should be ./node_modules created with a .bin
$ ./node_modules/.bin/akashacms init site
$ cd site
$ npm install
$ ../node_modules/.bin/akashacms build
```

**Comment by PhiLhoSoft** [comment]
Yes, this worked fine on a new computer with Windows 10.
Now I can start experimenting.
Many thanks.

**Comment by robogeek** [comment]
Cool... I'll update the website.

**Comment by robogeek** [comment]
I've updated the site: http://akashacms.com/install.html

Please let me know if this is sufficient.

**Comment by PhiLhoSoft** [comment]
Looks good. Note that when a path is for a project only, I just change the path in the command line (can make a .cmd file for that):
`set PATH=%PATH%;C:\Documents and Settings\David Herron\node_modules\.bin`
It will work as long as the console is opened.

**Comment by robogeek** [comment]
Updated the website

**Comment by PhiLhoSoft** [comment]
I made another try.
I installed akashacms-cli globally.
It works. The nice point here it that there is no need to mess with PATH, as the local npm folder is already in it.

I tried to install akashacms globally too (removing it from package.json), but it doesn't work, alas:
> $ akashacms build
> Could not find AkashaCMS because: Error: Cannot find module 'akashacms' from 'C:\PersonnelPhilippeLhoste\PhiLhoSoft\Web\AkashaCMSTest\PLS'

> If you're seeing this message, akashacms hasn't been
> installed locally.  You may need to type 'npm install'.
> See http://akashacms.com for more help

Too bad, that would have made 30 MB shared across projects...
But once I installed it with `npm i`, it worked.

For the record, the steps (without the attempt to use a global akashacms):


```
> cd AkashaCMSTest\
> npm i -g akashacms-cli
C:\Users\plhoste\AppData\Roaming\npm\akashacms -> C:\Users\plhoste\AppData\Roaming\npm\node_modules\akashacms-cli\cli.js
akashacms-cli@0.4.7 C:\Users\plhoste\AppData\Roaming\npm\node_modules\akashacms-cli
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── resolve@1.1.6
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.4, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.0, mime-types@2.1.7, form-data@1.0.0-rc3, http-signature@0.11.0, bl@1.0.0, hawk@3.1.1, har-validator@2.0.2)

> akashacms init PLS
Cloning into 'PLS'...
remote: Counting objects: 304, done.
remote: Total 304 (delta 0), reused 0 (delta 0), pack-reused 304
Receiving objects: 100% (304/304), 198.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (135/135), done.
Checking connectivity... done.

> cd PLS
> npm install
akashacms-theme-bootstrap@0.4.2 node_modules\akashacms-theme-bootstrap

akashacms-booknav@0.4.3 node_modules\akashacms-booknav
└── async@1.5.0

akashacms-base@0.4.4 node_modules\akashacms-base
└── async@1.5.0

akashacms-embeddables@0.4.3 node_modules\akashacms-embeddables
├── async@1.5.0
├── request@2.65.0 (forever-agent@0.6.1, aws-sign2@0.6.0, stringstream@0.0.5, caseless@0.11.0, tunnel-agent@0.4.1, oauth-sign@0.8.0, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.4, qs@5.2.0, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.1)
└── youtube-node@1.3.0 (colors@1.0.3, request@2.53.0, prompt@0.2.14)

akashacms@0.4.14 node_modules\akashacms
├── basic-auth@1.0.3
├── sightmap@0.0.1
├── mahabhuta@0.4.2
├── kernel@0.1.4
├── mime@1.3.4
├── formidable@1.0.17
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── async@1.5.0
├── body@5.1.0 (continuable-cache@0.3.1, safe-json-parse@1.0.1, raw-body@1.1.7, error@7.0.2)
├── sseasy@2.0.1 (through2@0.6.5)
├── rss@1.2.1 (xml@1.0.0, mime-types@2.1.7)
├── oembed@0.1.0 (htmlparser@1.7.7)
├── ejs@2.3.4
├── globfs@0.1.1 (glob@6.0.1)
├── fs-extra@0.26.2 (path-is-absolute@1.0.0, jsonfile@2.2.3, klaw@1.1.1, graceful-fs@4.1.2, rimraf@2.4.3)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, methods@1.1.1, cookie-signature@1.0.6, vary@1.0.1, range-parser@1.0.3, path-to-regexp@0.1.7, fresh@0.3.0, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, finalhandler@0.4.0, on-finished@2.3.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.9, accepts@1.2.13)
├── body-parser@1.14.1 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.4, debug@2.2.0, qs@5.1.0, type-is@1.6.9, iconv-lite@0.4.12)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, oauth-sign@0.8.0, tunnel-agent@0.4.1, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, combined-stream@1.0.5, node-uuid@1.4.4, qs@5.2.0, mime-types@2.1.7, tough-cookie@2.2.0, http-signature@0.11.0, bl@1.0.0, har-validator@2.0.2, hawk@3.1.1)
├── log4js@0.6.27 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.6)
├── ssh2sync@0.0.15 (filewalker@0.1.2, ssh2@0.4.12)
├── node-zip@1.1.1 (jszip@2.5.0)
├── minify@2.0.0 (try-catch@1.0.0, rendy@1.1.0, execon@1.2.9, debug@2.2.0, tomas@1.0.2, html-minifier@1.0.0, clean-css@3.4.7, css-b64-images@0.2.5, uglify-js@2.5.0)
├── yfm@0.2.0 (delims@0.1.4, fs-utils@0.1.11, lodash@2.4.2, js-yaml@3.0.2)
├── cheerio@0.19.0 (dom-serializer@0.1.0, entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3, lodash@3.10.1)
├── archiver@0.16.0 (buffer-crc32@0.2.5, async@1.4.2, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.6.0, glob@5.0.15, tar-stream@1.2.2, lodash@3.10.1)
├── markdown-it@5.0.1 (uc.micro@1.0.0, mdurl@1.0.1, linkify-it@1.2.0, entities@1.1.1, argparse@1.0.3)
└── less@2.5.3 (graceful-fs@3.0.8, image-size@0.3.5, source-map@0.4.4, promise@6.1.0, errno@0.1.4, mkdirp@0.5.1)

> akashacms build
[2015-11-12 16:26:15.037] [INFO] akashacms - removing out
[2015-11-12 16:26:15.045] [INFO] akashacms - making empty out
[2015-11-12 16:26:15.113] [INFO] akashacms - ******** gatherDir DIR documents
[2015-11-12 16:26:15.142] [INFO] akashacms - FILE 1 extra-scripts.html.md
[2015-11-12 16:26:15.253] [INFO] akashacms - rendered extra-scripts.html.md as out\extra-scripts.html
[2015-11-12 16:26:15.257] [INFO] akashacms - FILE 2 folder/folder/folder/index.html.md
[2015-11-12 16:26:15.305] [INFO] akashacms - rendered folder/folder/folder/index.html.md as out\folder\folder\folder\index.html
[2015-11-12 16:26:15.308] [INFO] akashacms - FILE 3 folder/folder/folder/page1.html.md
[2015-11-12 16:26:15.339] [INFO] akashacms - rendered folder/folder/folder/page1.html.md as out\folder\folder\folder\page1.html
[2015-11-12 16:26:15.341] [INFO] akashacms - FILE 4 folder/folder/folder/page2.html.md
[2015-11-12 16:26:15.377] [INFO] akashacms - rendered folder/folder/folder/page2.html.md as out\folder\folder\folder\page2.html
[2015-11-12 16:26:15.378] [INFO] akashacms - FILE 5 folder/folder/index.html.md
[2015-11-12 16:26:15.409] [INFO] akashacms - rendered folder/folder/index.html.md as out\folder\folder\index.html
[2015-11-12 16:26:15.410] [INFO] akashacms - FILE 6 folder/index.html.md
[2015-11-12 16:26:15.453] [INFO] akashacms - rendered folder/index.html.md as out\folder\index.html
[2015-11-12 16:26:15.455] [INFO] akashacms - FILE 7 index.html.ejs
[2015-11-12 16:26:15.486] [INFO] akashacms - rendered index.html.ejs as out\index.html
[2015-11-12 16:26:15.488] [INFO] akashacms - FILE 8 json-data.html.json
[2015-11-12 16:26:15.513] [INFO] akashacms - rendered json-data.html.json as out\json-data.html
[2015-11-12 16:26:15.515] [INFO] akashacms - FILE 9 mahabhuta.html.md
[2015-11-12 16:26:15.547] [INFO] akashacms - rendered mahabhuta.html.md as out\mahabhuta.html
[2015-11-12 16:26:15.549] [INFO] akashacms - FILE 10 markdown.html.md
[2015-11-12 16:26:15.593] [INFO] akashacms - rendered markdown.html.md as out\markdown.html
[2015-11-12 16:26:15.595] [INFO] akashacms - FILE 11 syncpartial.html.ejs
[2015-11-12 16:26:15.626] [INFO] akashacms - rendered syncpartial.html.ejs as out\syncpartial.html
[2015-11-12 16:26:15.628] [INFO] akashacms - FILE 12 twitter-embed.html.md
[2015-11-12 16:26:15.963] [ERROR] console - util.pump(): Use readableStream.pipe() instead
[2015-11-12 16:26:16.769] [INFO] akashacms - rendered twitter-embed.html.md as out\twitter-embed.html
[2015-11-12 16:26:16.771] [INFO] akashacms - FILE 13 video.html.md
[2015-11-12 16:26:17.519] [INFO] akashacms - rendered video.html.md as out\video.html
[2015-11-12 16:26:17.522] [INFO] akashacms - ***** renderDocuments saw count=13
[2015-11-12 16:26:17.522] [INFO] akashacms - about to generate sitemap
[2015-11-12 16:26:17.524] [INFO] akashacms - about to all-done
```
Instructions are simpler with a global install of the cli.
FTR...

**Comment by robogeek** [comment]
FYI - I took a hint from what you'd reported that the AkashaCMS install is too big.

The editor portion is now a separate package, akashacms-editor, that is optional.  https://github.com/akashacms/akashacms/issues/137

The size went from 

```
$ du -sk node_modules/*
106164  node_modules/akashacms
```

To

```
$ du -sk node_modules/*
80744   node_modules/akashacms
```
